import allImages from "./imageProvider";

//for images
const { categoryImages } = allImages;

const navItems = [
  { id: 1, name: "হোম", path: "/" },
  { id: 2, name: "বাজার দর", path: "/market-prices" },
  { id: 3, name: "বাজার সংবাদ", path: "/market-news" },
  { id: 4, name: "মূল্য জমা দিন", path: "/submit-price" },
  { id: 5, name: "ব্লগ", path: "/blog" },
  { id: 6, name: "সাধারণ প্রশ্ন", path: "/faq" },
  { id: 7, name: "আমাদের সম্পর্কে", path: "/about" },
];

const siteData = {
  topCities: [
    { id: 1, name: "ঢাকা", path: "/cities/dhaka" },
    { id: 2, name: "চট্টগ্রাম", path: "/cities/chattogram" },
    { id: 3, name: "খুলনা", path: "/cities/khulna" },
    { id: 4, name: "রাজশাহী", path: "/cities/rajshahi" },
    { id: 5, name: "সিলেট", path: "/cities/sylhet" },
  ],

  categories: [
    { id: 1, name: "সবজি", path: "/categories/vegetables" },
    { id: 2, name: "মুদির সামগ্রী", path: "/categories/grocery-staples" },
    {
      id: 3,
      name: "সকালের খাবার ও দুগ্ধজাত",
      path: "/categories/breakfast-dairy",
    },
    { id: 4, name: "সফট ড্রিঙ্কস", path: "/categories/soft-drinks" },
    { id: 5, name: "বিস্কুট ও কুকিজ", path: "/categories/biscuits-cookies" },
  ],

  aboutUs: [
    { id: 1, name: "কোম্পানির তথ্য", path: "/company-information" },
    { id: 2, name: "ক্যারিয়ার", path: "/careers" },
    { id: 3, name: "স্টোরের অবস্থান", path: "/store-location" },
    { id: 4, name: "অ্যাফিলিয়েট প্রোগ্রাম", path: "/affiliate-program" },
    { id: 5, name: "কপিরাইট", path: "/copyright" },
  ],
};
const categoriesItemsHeadings = [
  { id: 1, name: "সব পণ্য", slug: "all" },

  { id: 2, name: "চাল", slug: "rice" },

  { id: 3, name: "ডাল", slug: "lentils" },

  { id: 4, name: "শাকসবজি", slug: "vegetables" },

  { id: 5, name: "ফলমূল", slug: "fruits" },

  { id: 6, name: "মাছ", slug: "fish" },

  { id: 7, name: "মাংস", slug: "meat" },

  { id: 8, name: "ডিম", slug: "eggs" },

  { id: 9, name: "দুধ ও দুগ্ধজাত", slug: "milk-dairy" },

  { id: 10, name: "ভোজ্য তেল", slug: "edible-oil" },
];
const categoriesItems = [
  {
    id: 1,
    name: "চাল",
    image: categoryImages[0].img,
    bgColor: "#FDE2E2",
    slug: "rice",
    description: "B ভিটামিন ও শক্তি",
    price: "৳70-90 / কেজি",
  },
  {
    id: 2,
    name: "ডাল",
    image: categoryImages[1].img,
    bgColor: "#FFF0F5",
    slug: "lentils",
    description: "প্রোটিন ও ফাইবার",
    price: "৳110-140 / কেজি",
  },
  {
    id: 3,
    name: "শাকসবজি",
    image: categoryImages[2].img,
    bgColor: "#E6F7E6",
    slug: "vegetables",
    description: "ভিটামিন A, C, আয়রন",
    price: "৳40-80 / কেজি",
  },
  {
    id: 4,
    name: "ফলমূল",
    image: categoryImages[3].img,
    bgColor: "#FFF9E6",
    slug: "fruits",
    description: "ভিটামিন C, অ্যান্টি-অক্সিডেন্ট",
    price: "৳120-200 / কেজি",
  },
  {
    id: 5,
    name: "মাছ",
    image: categoryImages[4].img,
    bgColor: "#E0F7FF",
    slug: "fish",
    description: "ওমেগা-৩ ও প্রোটিন",
    price: "৳220-350 / কেজি",
  },
  {
    id: 6,
    name: "মাংস",
    image: categoryImages[5].img,
    bgColor: "#FFE6E6",
    slug: "meat",
    description: "প্রোটিন ও আয়রন",
    price: "৳650-750 / কেজি",
  },
  {
    id: 7,
    name: "ডিম",
    image: categoryImages[6].img,
    bgColor: "#FFF8E6",
    slug: "eggs",
    description: "প্রোটিন, D ভিটামিন",
    price: "৳130-150 / ডজন",
  },
  {
    id: 8,
    name: "দুধ ও দুগ্ধজাত",
    image: categoryImages[7].img,
    bgColor: "#E8F4FF",
    slug: "milk-dairy",
    description: "ক্যালসিয়াম ও D ভিটামিন",
    price: "৳80-100 / লিটার",
  },
  {
    id: 9,
    name: "ভোজ্য তেল",
    image: categoryImages[8].img,
    bgColor: "#FFF5E6",
    slug: "edible-oil",
    description: "স্বাস্থ্যকর ফ্যাট",
    price: "৳170-200 / লিটার",
  },
  {
    id: 10,
    name: "মসলা",
    image: categoryImages[9].img,
    bgColor: "#FFF0E6",
    slug: "spices",
    description: "অ্যান্টি-অক্সিডেন্ট",
    price: "৳400-900 / কেজি",
  },
  {
    id: 11,
    name: "আটা ও ময়দা",
    image: categoryImages[10].img,
    bgColor: "#FFFDF0",
    slug: "flour",
    description: "ফাইবার, B ভিটামিন",
    price: "৳55-70 / কেজি",
  },
  {
    id: 12,
    name: "চিনি",
    image: categoryImages[11].img,
    bgColor: "#FFF5F5",
    slug: "sugar",
    description: "দ্রুত শক্তি",
    price: "৳120-140 / কেজি",
  },
  {
    id: 13,
    name: "লবণ",
    image: categoryImages[12].img,
    bgColor: "#F0F0F0",
    slug: "salt",
    description: "সোডিয়াম, শরীর নিয়ন্ত্রণ",
    price: "৳35-45 / কেজি",
  },
  {
    id: 14,
    name: "চা ও কফি",
    image: categoryImages[13].img,
    bgColor: "#FFF3E6",
    slug: "tea-coffee",
    description: "অ্যান্টি-অক্সিডেন্ট, সতর্কতা",
    price: "৳450-900 / কেজি",
  },
  {
    id: 15,
    name: "পেঁয়াজ ও রসুন",
    image: categoryImages[14].img,
    bgColor: "#FFEFE6",
    slug: "onion-garlic",
    description: "অ্যান্টি-ব্যাকটেরিয়াল",
    price: "৳80-120 / কেজি",
  },
  {
    id: 16,
    name: "আলু",
    image: categoryImages[15].img,
    bgColor: "#FFFDE6",
    slug: "potato",
    description: "ভিটামিন C ও শক্তি",
    price: "৳30-40 / কেজি",
  },
];

const productPriceItems = [
  {
    id: 1,
    productName: "চাল",
    todayPrice: "৳85",
    yesterdayPrice: "৳80",
    dateTimes: "৬ মার্চ ২০২৬",
    srcImage: categoryImages[0].img,
    imgAlt: "চাল",
  },
  {
    id: 2,
    productName: "ডাল",
    todayPrice: "৳130",
    yesterdayPrice: "৳125",
    dateTimes: "৬ মার্চ ২০২৬",
    srcImage: categoryImages[1].img,
    imgAlt: "ডাল",
  },
  {
    id: 3,
    productName: "শাকসবজি",
    todayPrice: "৳60",
    yesterdayPrice: "৳55",
    dateTimes: "৬ মার্চ ২০২৬",
    srcImage: categoryImages[2].img,
    imgAlt: "শাকসবজি",
  },
  {
    id: 4,
    productName: "ফলমূল",
    todayPrice: "৳150",
    yesterdayPrice: "৳145",
    dateTimes: "৬ মার্চ ২০২৬",
    srcImage: categoryImages[3].img,
    imgAlt: "ফলমূল",
  },
  {
    id: 5,
    productName: "মাছ",
    todayPrice: "৳320",
    yesterdayPrice: "৳300",
    dateTimes: "৬ মার্চ ২০২৬",
    srcImage: categoryImages[4].img,
    imgAlt: "মাছ",
  },
  {
    id: 6,
    productName: "মাংস",
    todayPrice: "৳720",
    yesterdayPrice: "৳700",
    dateTimes: "৬ মার্চ ২০২৬",
    srcImage: categoryImages[5].img,
    imgAlt: "মাংস",
  },
  {
    id: 7,
    productName: "ডিম",
    todayPrice: "৳150",
    yesterdayPrice: "৳145",
    dateTimes: "৬ মার্চ ২০২৬",
    srcImage: categoryImages[6].img,
    imgAlt: "ডিম",
  },
  {
    id: 8,
    productName: "দুধ",
    todayPrice: "৳95",
    yesterdayPrice: "৳90",
    dateTimes: "৬ মার্চ ২০২৬",
    srcImage: categoryImages[7].img,
    imgAlt: "দুধ",
  },
  {
    id: 9,
    productName: "ভোজ্য তেল",
    todayPrice: "৳190",
    yesterdayPrice: "৳185",
    dateTimes: "৬ মার্চ ২০২৬",
    srcImage: categoryImages[8].img,
    imgAlt: "ভোজ্য তেল",
  },
  {
    id: 10,
    productName: "মসলা",
    todayPrice: "৳750",
    yesterdayPrice: "৳730",
    dateTimes: "৬ মার্চ ২০২৬",
    srcImage: categoryImages[9].img,
    imgAlt: "মসলা",
  },
  {
    id: 11,
    productName: "আটা",
    todayPrice: "৳65",
    yesterdayPrice: "৳63",
    dateTimes: "৬ মার্চ ২০২৬",
    srcImage: categoryImages[10].img,
    imgAlt: "আটা",
  },
  {
    id: 12,
    productName: "চিনি",
    todayPrice: "৳135",
    yesterdayPrice: "৳130",
    dateTimes: "৬ মার্চ ২০২৬",
    srcImage: categoryImages[11].img,
    imgAlt: "চিনি",
  },
  {
    id: 13,
    productName: "লবণ",
    todayPrice: "৳42",
    yesterdayPrice: "৳40",
    dateTimes: "৬ মার্চ ২০২৬",
    srcImage: categoryImages[12].img,
    imgAlt: "লবণ",
  },
  {
    id: 14,
    productName: "চা",
    todayPrice: "৳800",
    yesterdayPrice: "৳780",
    dateTimes: "৬ মার্চ ২০২৬",
    srcImage: categoryImages[13].img,
    imgAlt: "চা",
  },
  {
    id: 15,
    productName: "পেঁয়াজ",
    todayPrice: "৳110",
    yesterdayPrice: "৳105",
    dateTimes: "৬ মার্চ ২০২৬",
    srcImage: categoryImages[14].img,
    imgAlt: "পেঁয়াজ",
  },
  {
    id: 16,
    productName: "আলু",
    todayPrice: "৳38",
    yesterdayPrice: "৳35",
    dateTimes: "৬ মার্চ ২০২৬",
    srcImage: categoryImages[15].img,
    imgAlt: "আলু",
  },
];
const sortOptions = [
  { label: "ডিফল্ট সাজানো", value: "" },
  { label: "দাম কম থেকে বেশি", value: "price-asc" },
  { label: "দাম বেশি থেকে কম", value: "price-desc" },
  { label: "পণ্যের নাম (অ → হ)", value: "name-asc" },
  { label: "পণ্যের নাম (হ → অ)", value: "name-desc" },
];

// src/data/products.js

const productsBanner = [
  {
    id: 1,
    name: "পেঁয়াজ",
    type: "শাকসবজি",
    govtPrice: "৫০",
    marketPrice: "৫৫",
    weight: "১ কেজি",
    origin: "ঢাকা",
    storage: "ঠান্ডা ও শুকনো স্থান",
    stockPercent: 72,
    stockLabel: "পর্যাপ্ত",
    lastUpdated: "১২ মার্চ ২০২৬",
    note: "সরকারি সরবরাহকৃত পণ্য",
    image: "/images/onion.png",
  },
  {
    id: 2,
    name: "আলু",
    type: "শাকসবজি",
    govtPrice: "৩০",
    marketPrice: "৩৫",
    weight: "১ কেজি",
    origin: "মুন্সীগঞ্জ",
    storage: "ঠান্ডা ও শুকনো স্থান",
    stockPercent: 85,
    stockLabel: "পর্যাপ্ত",
    lastUpdated: "১২ মার্চ ২০২৬",
    note: "সরকারি সরবরাহকৃত পণ্য",
    image: "/images/potato.png",
  },
  {
    id: 3,
    name: "রসুন",
    type: "শাকসবজি",
    govtPrice: "১২০",
    marketPrice: "১৪০",
    weight: "১ কেজি",
    origin: "রাজশাহী",
    storage: "ঠান্ডা ও শুকনো স্থান",
    stockPercent: 60,
    stockLabel: "মধ্যম",
    lastUpdated: "১২ মার্চ ২০২৬",
    note: "সরকারি সরবরাহকৃত পণ্য",
    image: "/images/garlic.png",
  },
  {
    id: 4,
    name: "আদা",
    type: "মশলা",
    govtPrice: "৮০",
    marketPrice: "৯৫",
    weight: "১ কেজি",
    origin: "সিলেট",
    storage: "ঠান্ডা ও শুকনো স্থান",
    stockPercent: 55,
    stockLabel: "মধ্যম",
    lastUpdated: "১২ মার্চ ২০২৬",
    note: "সরকারি সরবরাহকৃত পণ্য",
    image: "/images/ginger.png",
  },
  {
    id: 5,
    name: "হলুদ",
    type: "মশলা",
    govtPrice: "১৫০",
    marketPrice: "১৬০",
    weight: "১ কেজি",
    origin: "কুমিল্লা",
    storage: "ঠান্ডা ও শুকনো স্থান",
    stockPercent: 90,
    stockLabel: "পর্যাপ্ত",
    lastUpdated: "১২ মার্চ ২০২৬",
    note: "সরকারি সরবরাহকৃত পণ্য",
    image: "/images/turmeric.png",
  },
  {
    id: 6,
    name: "মরিচ",
    type: "মশলা",
    govtPrice: "২০০",
    marketPrice: "২৩০",
    weight: "১ কেজি",
    origin: "বগুড়া",
    storage: "ঠান্ডা ও শুকনো স্থান",
    stockPercent: 45,
    stockLabel: "সীমিত",
    lastUpdated: "১২ মার্চ ২০২৬",
    note: "সরকারি সরবরাহকৃত পণ্য",
    image: "/images/chili.png",
  },
  {
    id: 7,
    name: "টমেটো",
    type: "শাকসবজি",
    govtPrice: "৬০",
    marketPrice: "৬৫",
    weight: "১ কেজি",
    origin: "যশোর",
    storage: "ঘরের তাপমাত্রায় রাখুন",
    stockPercent: 78,
    stockLabel: "পর্যাপ্ত",
    lastUpdated: "১২ মার্চ ২০২৬",
    note: "সরকারি সরবরাহকৃত পণ্য",
    image: "/images/tomato.png",
  },
  {
    id: 8,
    name: "বেগুন",
    type: "শাকসবজি",
    govtPrice: "৪০",
    marketPrice: "৪৫",
    weight: "১ কেজি",
    origin: "নরসিংদী",
    storage: "ঘরের তাপমাত্রায় রাখুন",
    stockPercent: 80,
    stockLabel: "পর্যাপ্ত",
    lastUpdated: "১২ মার্চ ২০২৬",
    note: "সরকারি সরবরাহকৃত পণ্য",
    image: "/images/eggplant.png",
  },
  {
    id: 9,
    name: "ডাল",
    type: "শস্য",
    govtPrice: "৯০",
    marketPrice: "১০০",
    weight: "১ কেজি",
    origin: "দিনাজপুর",
    storage: "শুকনো ও বায়ুরোধী পাত্রে রাখুন",
    stockPercent: 95,
    stockLabel: "পর্যাপ্ত",
    lastUpdated: "১২ মার্চ ২০২৬",
    note: "সরকারি সরবরাহকৃত পণ্য",
    image: "/images/lentil.png",
  },
  {
    id: 10,
    name: "চাল",
    type: "শস্য",
    govtPrice: "৫৫",
    marketPrice: "৬০",
    weight: "১ কেজি",
    origin: "নওগাঁ",
    storage: "শুকনো ও বায়ুরোধী পাত্রে রাখুন",
    stockPercent: 88,
    stockLabel: "পর্যাপ্ত",
    lastUpdated: "১২ মার্চ ২০২৬",
    note: "সরকারি সরবরাহকৃত পণ্য",
    image: "/images/rice.png",
  },
  {
    id: 11,
    name: "গম",
    type: "শস্য",
    govtPrice: "৪৫",
    marketPrice: "৫০",
    weight: "১ কেজি",
    origin: "রাজশাহী",
    storage: "শুকনো ও বায়ুরোধী পাত্রে রাখুন",
    stockPercent: 70,
    stockLabel: "পর্যাপ্ত",
    lastUpdated: "১২ মার্চ ২০২৬",
    note: "সরকারি সরবরাহকৃত পণ্য",
    image: "/images/wheat.png",
  },
  {
    id: 12,
    name: "সয়াবিন তেল",
    type: "তেল",
    govtPrice: "১৬০",
    marketPrice: "১৭৫",
    weight: "১ লিটার",
    origin: "ঢাকা",
    storage: "ঠান্ডা ও শুকনো স্থান",
    stockPercent: 65,
    stockLabel: "মধ্যম",
    lastUpdated: "১২ মার্চ ২০২৬",
    note: "সরকারি সরবরাহকৃত পণ্য",
    image: "/images/soybean-oil.png",
  },
  {
    id: 13,
    name: "চিনি",
    type: "মিষ্টি",
    govtPrice: "১৩০",
    marketPrice: "১৪০",
    weight: "১ কেজি",
    origin: "ঢাকা",
    storage: "শুকনো ও বায়ুরোধী পাত্রে রাখুন",
    stockPercent: 82,
    stockLabel: "পর্যাপ্ত",
    lastUpdated: "১২ মার্চ ২০২৬",
    note: "সরকারি সরবরাহকৃত পণ্য",
    image: "/images/sugar.png",
  },
  {
    id: 14,
    name: "লবণ",
    type: "মশলা",
    govtPrice: "৩৫",
    marketPrice: "৩৮",
    weight: "১ কেজি",
    origin: "কক্সবাজার",
    storage: "শুকনো ও বায়ুরোধী পাত্রে রাখুন",
    stockPercent: 95,
    stockLabel: "পর্যাপ্ত",
    lastUpdated: "১২ মার্চ ২০২৬",
    note: "সরকারি সরবরাহকৃত পণ্য",
    image: "/images/salt.png",
  },
  {
    id: 15,
    name: "ডিম",
    type: "প্রোটিন",
    govtPrice: "১২",
    marketPrice: "১৪",
    weight: "১টি",
    origin: "গাজীপুর",
    storage: "ফ্রিজে সংরক্ষণ করে রাখুন",
    stockPercent: 75,
    stockLabel: "পর্যাপ্ত",
    lastUpdated: "১২ মার্চ ২০২৬",
    note: "সরকারি সরবরাহকৃত পণ্য",
    image: "/images/egg.png",
  },
  {
    id: 16,
    name: "মুরগি",
    type: "প্রোটিন",
    govtPrice: "১৮০",
    marketPrice: "২১০",
    weight: "১ কেজি",
    origin: "ময়মনসিংহ",
    storage: "ফ্রিজে সংরক্ষণ করে রাখুন",
    stockPercent: 50,
    stockLabel: "সীমিত",
    lastUpdated: "১২ মার্চ ২০২৬",
    note: "সরকারি সরবরাহকৃত পণ্য",
    image: "/images/chicken.png",
  },
];

export {
  navItems,
  siteData,
  categoriesItemsHeadings,
  categoriesItems,
  productPriceItems,
  sortOptions,
  productsBanner,
};
